name: flconf
description: A CLI tool to help run flutter app from config file
version: 1.0.0
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/flconf
issue_tracker: https://github.com/Mankeli-Software/flconf/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0

executables:
  flconf: main
